//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TekManager.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginAttemptDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LoginAttemptDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterAttemptDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RegisterAttemptDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ConfirmPassword {
            get {
                return this.ConfirmPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmPasswordField, value) != true)) {
                    this.ConfirmPasswordField = value;
                    this.RaisePropertyChanged("ConfirmPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordResetDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PasswordResetDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResetGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResetGuid {
            get {
                return this.ResetGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ResetGuidField, value) != true)) {
                    this.ResetGuidField = value;
                    this.RaisePropertyChanged("ResetGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSqlModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductSqlModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        private decimal AveragePriceField;
        
        private decimal BuyPriceField;
        
        private decimal SellPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        private int StockField;
        
        private bool ActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal AveragePrice {
            get {
                return this.AveragePriceField;
            }
            set {
                if ((this.AveragePriceField.Equals(value) != true)) {
                    this.AveragePriceField = value;
                    this.RaisePropertyChanged("AveragePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal BuyPrice {
            get {
                return this.BuyPriceField;
            }
            set {
                if ((this.BuyPriceField.Equals(value) != true)) {
                    this.BuyPriceField = value;
                    this.RaisePropertyChanged("BuyPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal SellPrice {
            get {
                return this.SellPriceField;
            }
            set {
                if ((this.SellPriceField.Equals(value) != true)) {
                    this.SellPriceField = value;
                    this.RaisePropertyChanged("SellPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberSqlModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MemberSqlModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.DataServiceSoap")]
    public interface DataServiceSoap {
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        TekManager.DataService.LoginResponse Login(TekManager.DataService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<TekManager.DataService.LoginResponse> LoginAsync(TekManager.DataService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name model from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        TekManager.DataService.RegisterResponse Register(TekManager.DataService.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<TekManager.DataService.RegisterResponse> RegisterAsync(TekManager.DataService.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateResetEmailRequest", ReplyAction="*")]
        TekManager.DataService.CreateResetEmailRequestResponse CreateResetEmailRequest(TekManager.DataService.CreateResetEmailRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateResetEmailRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<TekManager.DataService.CreateResetEmailRequestResponse> CreateResetEmailRequestAsync(TekManager.DataService.CreateResetEmailRequestRequest request);
        
        // CODEGEN: Generating message contract since element name guid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CanResetPassword", ReplyAction="*")]
        TekManager.DataService.CanResetPasswordResponse CanResetPassword(TekManager.DataService.CanResetPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CanResetPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<TekManager.DataService.CanResetPasswordResponse> CanResetPasswordAsync(TekManager.DataService.CanResetPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetPassword", ReplyAction="*")]
        TekManager.DataService.ResetPasswordResponse ResetPassword(TekManager.DataService.ResetPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResetPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<TekManager.DataService.ResetPasswordResponse> ResetPasswordAsync(TekManager.DataService.ResetPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name commaIds from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        TekManager.DataService.GetProductsResponse GetProducts(TekManager.DataService.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<TekManager.DataService.GetProductsResponse> GetProductsAsync(TekManager.DataService.GetProductsRequest request);
        
        // CODEGEN: Generating message contract since element name category from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsByPage", ReplyAction="*")]
        TekManager.DataService.GetProductsByPageResponse GetProductsByPage(TekManager.DataService.GetProductsByPageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsByPage", ReplyAction="*")]
        System.Threading.Tasks.Task<TekManager.DataService.GetProductsByPageResponse> GetProductsByPageAsync(TekManager.DataService.GetProductsByPageRequest request);
        
        // CODEGEN: Generating message contract since element name partialName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsByPartial", ReplyAction="*")]
        TekManager.DataService.GetProductsByPartialResponse GetProductsByPartial(TekManager.DataService.GetProductsByPartialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsByPartial", ReplyAction="*")]
        System.Threading.Tasks.Task<TekManager.DataService.GetProductsByPartialResponse> GetProductsByPartialAsync(TekManager.DataService.GetProductsByPartialRequest request);
        
        // CODEGEN: Generating message contract since element name partialName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActiveProductsByPartial", ReplyAction="*")]
        TekManager.DataService.GetActiveProductsByPartialResponse GetActiveProductsByPartial(TekManager.DataService.GetActiveProductsByPartialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActiveProductsByPartial", ReplyAction="*")]
        System.Threading.Tasks.Task<TekManager.DataService.GetActiveProductsByPartialResponse> GetActiveProductsByPartialAsync(TekManager.DataService.GetActiveProductsByPartialRequest request);
        
        // CODEGEN: Generating message contract since element name product from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveProduct", ReplyAction="*")]
        TekManager.DataService.SaveProductResponse SaveProduct(TekManager.DataService.SaveProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<TekManager.DataService.SaveProductResponse> SaveProductAsync(TekManager.DataService.SaveProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        int DeleteProduct(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DeleteProductAsync(int productId);
        
        // CODEGEN: Generating message contract since element name searchTerm from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMembersByEmailOrId", ReplyAction="*")]
        TekManager.DataService.GetMembersByEmailOrIdResponse GetMembersByEmailOrId(TekManager.DataService.GetMembersByEmailOrIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMembersByEmailOrId", ReplyAction="*")]
        System.Threading.Tasks.Task<TekManager.DataService.GetMembersByEmailOrIdResponse> GetMembersByEmailOrIdAsync(TekManager.DataService.GetMembersByEmailOrIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(TekManager.DataService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TekManager.DataService.LoginAttemptDto details;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(TekManager.DataService.LoginAttemptDto details) {
            this.details = details;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(TekManager.DataService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(int LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(TekManager.DataService.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TekManager.DataService.RegisterAttemptDto model;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(TekManager.DataService.RegisterAttemptDto model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(TekManager.DataService.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TekManager.DataService.ArrayOfString RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(TekManager.DataService.ArrayOfString RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResetEmailRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResetEmailRequest", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.CreateResetEmailRequestRequestBody Body;
        
        public CreateResetEmailRequestRequest() {
        }
        
        public CreateResetEmailRequestRequest(TekManager.DataService.CreateResetEmailRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateResetEmailRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public CreateResetEmailRequestRequestBody() {
        }
        
        public CreateResetEmailRequestRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResetEmailRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResetEmailRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.CreateResetEmailRequestResponseBody Body;
        
        public CreateResetEmailRequestResponse() {
        }
        
        public CreateResetEmailRequestResponse(TekManager.DataService.CreateResetEmailRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateResetEmailRequestResponseBody {
        
        public CreateResetEmailRequestResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CanResetPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CanResetPassword", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.CanResetPasswordRequestBody Body;
        
        public CanResetPasswordRequest() {
        }
        
        public CanResetPasswordRequest(TekManager.DataService.CanResetPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CanResetPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string guid;
        
        public CanResetPasswordRequestBody() {
        }
        
        public CanResetPasswordRequestBody(string guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CanResetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CanResetPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.CanResetPasswordResponseBody Body;
        
        public CanResetPasswordResponse() {
        }
        
        public CanResetPasswordResponse(TekManager.DataService.CanResetPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CanResetPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CanResetPasswordResult;
        
        public CanResetPasswordResponseBody() {
        }
        
        public CanResetPasswordResponseBody(bool CanResetPasswordResult) {
            this.CanResetPasswordResult = CanResetPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetPassword", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.ResetPasswordRequestBody Body;
        
        public ResetPasswordRequest() {
        }
        
        public ResetPasswordRequest(TekManager.DataService.ResetPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResetPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TekManager.DataService.PasswordResetDto details;
        
        public ResetPasswordRequestBody() {
        }
        
        public ResetPasswordRequestBody(TekManager.DataService.PasswordResetDto details) {
            this.details = details;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.ResetPasswordResponseBody Body;
        
        public ResetPasswordResponse() {
        }
        
        public ResetPasswordResponse(TekManager.DataService.ResetPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ResetPasswordResponseBody {
        
        public ResetPasswordResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProducts", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.GetProductsRequestBody Body;
        
        public GetProductsRequest() {
        }
        
        public GetProductsRequest(TekManager.DataService.GetProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string commaIds;
        
        public GetProductsRequestBody() {
        }
        
        public GetProductsRequestBody(string commaIds) {
            this.commaIds = commaIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.GetProductsResponseBody Body;
        
        public GetProductsResponse() {
        }
        
        public GetProductsResponse(TekManager.DataService.GetProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TekManager.DataService.ProductSqlModel[] GetProductsResult;
        
        public GetProductsResponseBody() {
        }
        
        public GetProductsResponseBody(TekManager.DataService.ProductSqlModel[] GetProductsResult) {
            this.GetProductsResult = GetProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsByPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsByPage", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.GetProductsByPageRequestBody Body;
        
        public GetProductsByPageRequest() {
        }
        
        public GetProductsByPageRequest(TekManager.DataService.GetProductsByPageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsByPageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string category;
        
        public GetProductsByPageRequestBody() {
        }
        
        public GetProductsByPageRequestBody(int pageNumber, string category) {
            this.pageNumber = pageNumber;
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsByPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsByPageResponse", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.GetProductsByPageResponseBody Body;
        
        public GetProductsByPageResponse() {
        }
        
        public GetProductsByPageResponse(TekManager.DataService.GetProductsByPageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsByPageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TekManager.DataService.ProductSqlModel[] GetProductsByPageResult;
        
        public GetProductsByPageResponseBody() {
        }
        
        public GetProductsByPageResponseBody(TekManager.DataService.ProductSqlModel[] GetProductsByPageResult) {
            this.GetProductsByPageResult = GetProductsByPageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsByPartialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsByPartial", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.GetProductsByPartialRequestBody Body;
        
        public GetProductsByPartialRequest() {
        }
        
        public GetProductsByPartialRequest(TekManager.DataService.GetProductsByPartialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsByPartialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partialName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int count;
        
        public GetProductsByPartialRequestBody() {
        }
        
        public GetProductsByPartialRequestBody(string partialName, int count) {
            this.partialName = partialName;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsByPartialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsByPartialResponse", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.GetProductsByPartialResponseBody Body;
        
        public GetProductsByPartialResponse() {
        }
        
        public GetProductsByPartialResponse(TekManager.DataService.GetProductsByPartialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsByPartialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TekManager.DataService.ProductSqlModel[] GetProductsByPartialResult;
        
        public GetProductsByPartialResponseBody() {
        }
        
        public GetProductsByPartialResponseBody(TekManager.DataService.ProductSqlModel[] GetProductsByPartialResult) {
            this.GetProductsByPartialResult = GetProductsByPartialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveProductsByPartialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveProductsByPartial", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.GetActiveProductsByPartialRequestBody Body;
        
        public GetActiveProductsByPartialRequest() {
        }
        
        public GetActiveProductsByPartialRequest(TekManager.DataService.GetActiveProductsByPartialRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActiveProductsByPartialRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partialName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int count;
        
        public GetActiveProductsByPartialRequestBody() {
        }
        
        public GetActiveProductsByPartialRequestBody(string partialName, int count) {
            this.partialName = partialName;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActiveProductsByPartialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActiveProductsByPartialResponse", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.GetActiveProductsByPartialResponseBody Body;
        
        public GetActiveProductsByPartialResponse() {
        }
        
        public GetActiveProductsByPartialResponse(TekManager.DataService.GetActiveProductsByPartialResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActiveProductsByPartialResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TekManager.DataService.ProductSqlModel[] GetActiveProductsByPartialResult;
        
        public GetActiveProductsByPartialResponseBody() {
        }
        
        public GetActiveProductsByPartialResponseBody(TekManager.DataService.ProductSqlModel[] GetActiveProductsByPartialResult) {
            this.GetActiveProductsByPartialResult = GetActiveProductsByPartialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveProduct", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.SaveProductRequestBody Body;
        
        public SaveProductRequest() {
        }
        
        public SaveProductRequest(TekManager.DataService.SaveProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TekManager.DataService.ProductSqlModel product;
        
        public SaveProductRequestBody() {
        }
        
        public SaveProductRequestBody(TekManager.DataService.ProductSqlModel product) {
            this.product = product;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.SaveProductResponseBody Body;
        
        public SaveProductResponse() {
        }
        
        public SaveProductResponse(TekManager.DataService.SaveProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveProductResult;
        
        public SaveProductResponseBody() {
        }
        
        public SaveProductResponseBody(int SaveProductResult) {
            this.SaveProductResult = SaveProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMembersByEmailOrIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMembersByEmailOrId", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.GetMembersByEmailOrIdRequestBody Body;
        
        public GetMembersByEmailOrIdRequest() {
        }
        
        public GetMembersByEmailOrIdRequest(TekManager.DataService.GetMembersByEmailOrIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMembersByEmailOrIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchTerm;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int count;
        
        public GetMembersByEmailOrIdRequestBody() {
        }
        
        public GetMembersByEmailOrIdRequestBody(string searchTerm, int count) {
            this.searchTerm = searchTerm;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMembersByEmailOrIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMembersByEmailOrIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public TekManager.DataService.GetMembersByEmailOrIdResponseBody Body;
        
        public GetMembersByEmailOrIdResponse() {
        }
        
        public GetMembersByEmailOrIdResponse(TekManager.DataService.GetMembersByEmailOrIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMembersByEmailOrIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TekManager.DataService.MemberSqlModel[] GetMembersByEmailOrIdResult;
        
        public GetMembersByEmailOrIdResponseBody() {
        }
        
        public GetMembersByEmailOrIdResponseBody(TekManager.DataService.MemberSqlModel[] GetMembersByEmailOrIdResult) {
            this.GetMembersByEmailOrIdResult = GetMembersByEmailOrIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceSoapChannel : TekManager.DataService.DataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceSoapClient : System.ServiceModel.ClientBase<TekManager.DataService.DataServiceSoap>, TekManager.DataService.DataServiceSoap {
        
        public DataServiceSoapClient() {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TekManager.DataService.LoginResponse TekManager.DataService.DataServiceSoap.Login(TekManager.DataService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public int Login(TekManager.DataService.LoginAttemptDto details) {
            TekManager.DataService.LoginRequest inValue = new TekManager.DataService.LoginRequest();
            inValue.Body = new TekManager.DataService.LoginRequestBody();
            inValue.Body.details = details;
            TekManager.DataService.LoginResponse retVal = ((TekManager.DataService.DataServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TekManager.DataService.LoginResponse> TekManager.DataService.DataServiceSoap.LoginAsync(TekManager.DataService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<TekManager.DataService.LoginResponse> LoginAsync(TekManager.DataService.LoginAttemptDto details) {
            TekManager.DataService.LoginRequest inValue = new TekManager.DataService.LoginRequest();
            inValue.Body = new TekManager.DataService.LoginRequestBody();
            inValue.Body.details = details;
            return ((TekManager.DataService.DataServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TekManager.DataService.RegisterResponse TekManager.DataService.DataServiceSoap.Register(TekManager.DataService.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public TekManager.DataService.ArrayOfString Register(TekManager.DataService.RegisterAttemptDto model) {
            TekManager.DataService.RegisterRequest inValue = new TekManager.DataService.RegisterRequest();
            inValue.Body = new TekManager.DataService.RegisterRequestBody();
            inValue.Body.model = model;
            TekManager.DataService.RegisterResponse retVal = ((TekManager.DataService.DataServiceSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TekManager.DataService.RegisterResponse> TekManager.DataService.DataServiceSoap.RegisterAsync(TekManager.DataService.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<TekManager.DataService.RegisterResponse> RegisterAsync(TekManager.DataService.RegisterAttemptDto model) {
            TekManager.DataService.RegisterRequest inValue = new TekManager.DataService.RegisterRequest();
            inValue.Body = new TekManager.DataService.RegisterRequestBody();
            inValue.Body.model = model;
            return ((TekManager.DataService.DataServiceSoap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TekManager.DataService.CreateResetEmailRequestResponse TekManager.DataService.DataServiceSoap.CreateResetEmailRequest(TekManager.DataService.CreateResetEmailRequestRequest request) {
            return base.Channel.CreateResetEmailRequest(request);
        }
        
        public void CreateResetEmailRequest(string email) {
            TekManager.DataService.CreateResetEmailRequestRequest inValue = new TekManager.DataService.CreateResetEmailRequestRequest();
            inValue.Body = new TekManager.DataService.CreateResetEmailRequestRequestBody();
            inValue.Body.email = email;
            TekManager.DataService.CreateResetEmailRequestResponse retVal = ((TekManager.DataService.DataServiceSoap)(this)).CreateResetEmailRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TekManager.DataService.CreateResetEmailRequestResponse> TekManager.DataService.DataServiceSoap.CreateResetEmailRequestAsync(TekManager.DataService.CreateResetEmailRequestRequest request) {
            return base.Channel.CreateResetEmailRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<TekManager.DataService.CreateResetEmailRequestResponse> CreateResetEmailRequestAsync(string email) {
            TekManager.DataService.CreateResetEmailRequestRequest inValue = new TekManager.DataService.CreateResetEmailRequestRequest();
            inValue.Body = new TekManager.DataService.CreateResetEmailRequestRequestBody();
            inValue.Body.email = email;
            return ((TekManager.DataService.DataServiceSoap)(this)).CreateResetEmailRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TekManager.DataService.CanResetPasswordResponse TekManager.DataService.DataServiceSoap.CanResetPassword(TekManager.DataService.CanResetPasswordRequest request) {
            return base.Channel.CanResetPassword(request);
        }
        
        public bool CanResetPassword(string guid) {
            TekManager.DataService.CanResetPasswordRequest inValue = new TekManager.DataService.CanResetPasswordRequest();
            inValue.Body = new TekManager.DataService.CanResetPasswordRequestBody();
            inValue.Body.guid = guid;
            TekManager.DataService.CanResetPasswordResponse retVal = ((TekManager.DataService.DataServiceSoap)(this)).CanResetPassword(inValue);
            return retVal.Body.CanResetPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TekManager.DataService.CanResetPasswordResponse> TekManager.DataService.DataServiceSoap.CanResetPasswordAsync(TekManager.DataService.CanResetPasswordRequest request) {
            return base.Channel.CanResetPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<TekManager.DataService.CanResetPasswordResponse> CanResetPasswordAsync(string guid) {
            TekManager.DataService.CanResetPasswordRequest inValue = new TekManager.DataService.CanResetPasswordRequest();
            inValue.Body = new TekManager.DataService.CanResetPasswordRequestBody();
            inValue.Body.guid = guid;
            return ((TekManager.DataService.DataServiceSoap)(this)).CanResetPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TekManager.DataService.ResetPasswordResponse TekManager.DataService.DataServiceSoap.ResetPassword(TekManager.DataService.ResetPasswordRequest request) {
            return base.Channel.ResetPassword(request);
        }
        
        public void ResetPassword(TekManager.DataService.PasswordResetDto details) {
            TekManager.DataService.ResetPasswordRequest inValue = new TekManager.DataService.ResetPasswordRequest();
            inValue.Body = new TekManager.DataService.ResetPasswordRequestBody();
            inValue.Body.details = details;
            TekManager.DataService.ResetPasswordResponse retVal = ((TekManager.DataService.DataServiceSoap)(this)).ResetPassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TekManager.DataService.ResetPasswordResponse> TekManager.DataService.DataServiceSoap.ResetPasswordAsync(TekManager.DataService.ResetPasswordRequest request) {
            return base.Channel.ResetPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<TekManager.DataService.ResetPasswordResponse> ResetPasswordAsync(TekManager.DataService.PasswordResetDto details) {
            TekManager.DataService.ResetPasswordRequest inValue = new TekManager.DataService.ResetPasswordRequest();
            inValue.Body = new TekManager.DataService.ResetPasswordRequestBody();
            inValue.Body.details = details;
            return ((TekManager.DataService.DataServiceSoap)(this)).ResetPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TekManager.DataService.GetProductsResponse TekManager.DataService.DataServiceSoap.GetProducts(TekManager.DataService.GetProductsRequest request) {
            return base.Channel.GetProducts(request);
        }
        
        public TekManager.DataService.ProductSqlModel[] GetProducts(string commaIds) {
            TekManager.DataService.GetProductsRequest inValue = new TekManager.DataService.GetProductsRequest();
            inValue.Body = new TekManager.DataService.GetProductsRequestBody();
            inValue.Body.commaIds = commaIds;
            TekManager.DataService.GetProductsResponse retVal = ((TekManager.DataService.DataServiceSoap)(this)).GetProducts(inValue);
            return retVal.Body.GetProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TekManager.DataService.GetProductsResponse> TekManager.DataService.DataServiceSoap.GetProductsAsync(TekManager.DataService.GetProductsRequest request) {
            return base.Channel.GetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TekManager.DataService.GetProductsResponse> GetProductsAsync(string commaIds) {
            TekManager.DataService.GetProductsRequest inValue = new TekManager.DataService.GetProductsRequest();
            inValue.Body = new TekManager.DataService.GetProductsRequestBody();
            inValue.Body.commaIds = commaIds;
            return ((TekManager.DataService.DataServiceSoap)(this)).GetProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TekManager.DataService.GetProductsByPageResponse TekManager.DataService.DataServiceSoap.GetProductsByPage(TekManager.DataService.GetProductsByPageRequest request) {
            return base.Channel.GetProductsByPage(request);
        }
        
        public TekManager.DataService.ProductSqlModel[] GetProductsByPage(int pageNumber, string category) {
            TekManager.DataService.GetProductsByPageRequest inValue = new TekManager.DataService.GetProductsByPageRequest();
            inValue.Body = new TekManager.DataService.GetProductsByPageRequestBody();
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.category = category;
            TekManager.DataService.GetProductsByPageResponse retVal = ((TekManager.DataService.DataServiceSoap)(this)).GetProductsByPage(inValue);
            return retVal.Body.GetProductsByPageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TekManager.DataService.GetProductsByPageResponse> TekManager.DataService.DataServiceSoap.GetProductsByPageAsync(TekManager.DataService.GetProductsByPageRequest request) {
            return base.Channel.GetProductsByPageAsync(request);
        }
        
        public System.Threading.Tasks.Task<TekManager.DataService.GetProductsByPageResponse> GetProductsByPageAsync(int pageNumber, string category) {
            TekManager.DataService.GetProductsByPageRequest inValue = new TekManager.DataService.GetProductsByPageRequest();
            inValue.Body = new TekManager.DataService.GetProductsByPageRequestBody();
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.category = category;
            return ((TekManager.DataService.DataServiceSoap)(this)).GetProductsByPageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TekManager.DataService.GetProductsByPartialResponse TekManager.DataService.DataServiceSoap.GetProductsByPartial(TekManager.DataService.GetProductsByPartialRequest request) {
            return base.Channel.GetProductsByPartial(request);
        }
        
        public TekManager.DataService.ProductSqlModel[] GetProductsByPartial(string partialName, int count) {
            TekManager.DataService.GetProductsByPartialRequest inValue = new TekManager.DataService.GetProductsByPartialRequest();
            inValue.Body = new TekManager.DataService.GetProductsByPartialRequestBody();
            inValue.Body.partialName = partialName;
            inValue.Body.count = count;
            TekManager.DataService.GetProductsByPartialResponse retVal = ((TekManager.DataService.DataServiceSoap)(this)).GetProductsByPartial(inValue);
            return retVal.Body.GetProductsByPartialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TekManager.DataService.GetProductsByPartialResponse> TekManager.DataService.DataServiceSoap.GetProductsByPartialAsync(TekManager.DataService.GetProductsByPartialRequest request) {
            return base.Channel.GetProductsByPartialAsync(request);
        }
        
        public System.Threading.Tasks.Task<TekManager.DataService.GetProductsByPartialResponse> GetProductsByPartialAsync(string partialName, int count) {
            TekManager.DataService.GetProductsByPartialRequest inValue = new TekManager.DataService.GetProductsByPartialRequest();
            inValue.Body = new TekManager.DataService.GetProductsByPartialRequestBody();
            inValue.Body.partialName = partialName;
            inValue.Body.count = count;
            return ((TekManager.DataService.DataServiceSoap)(this)).GetProductsByPartialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TekManager.DataService.GetActiveProductsByPartialResponse TekManager.DataService.DataServiceSoap.GetActiveProductsByPartial(TekManager.DataService.GetActiveProductsByPartialRequest request) {
            return base.Channel.GetActiveProductsByPartial(request);
        }
        
        public TekManager.DataService.ProductSqlModel[] GetActiveProductsByPartial(string partialName, int count) {
            TekManager.DataService.GetActiveProductsByPartialRequest inValue = new TekManager.DataService.GetActiveProductsByPartialRequest();
            inValue.Body = new TekManager.DataService.GetActiveProductsByPartialRequestBody();
            inValue.Body.partialName = partialName;
            inValue.Body.count = count;
            TekManager.DataService.GetActiveProductsByPartialResponse retVal = ((TekManager.DataService.DataServiceSoap)(this)).GetActiveProductsByPartial(inValue);
            return retVal.Body.GetActiveProductsByPartialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TekManager.DataService.GetActiveProductsByPartialResponse> TekManager.DataService.DataServiceSoap.GetActiveProductsByPartialAsync(TekManager.DataService.GetActiveProductsByPartialRequest request) {
            return base.Channel.GetActiveProductsByPartialAsync(request);
        }
        
        public System.Threading.Tasks.Task<TekManager.DataService.GetActiveProductsByPartialResponse> GetActiveProductsByPartialAsync(string partialName, int count) {
            TekManager.DataService.GetActiveProductsByPartialRequest inValue = new TekManager.DataService.GetActiveProductsByPartialRequest();
            inValue.Body = new TekManager.DataService.GetActiveProductsByPartialRequestBody();
            inValue.Body.partialName = partialName;
            inValue.Body.count = count;
            return ((TekManager.DataService.DataServiceSoap)(this)).GetActiveProductsByPartialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TekManager.DataService.SaveProductResponse TekManager.DataService.DataServiceSoap.SaveProduct(TekManager.DataService.SaveProductRequest request) {
            return base.Channel.SaveProduct(request);
        }
        
        public int SaveProduct(TekManager.DataService.ProductSqlModel product) {
            TekManager.DataService.SaveProductRequest inValue = new TekManager.DataService.SaveProductRequest();
            inValue.Body = new TekManager.DataService.SaveProductRequestBody();
            inValue.Body.product = product;
            TekManager.DataService.SaveProductResponse retVal = ((TekManager.DataService.DataServiceSoap)(this)).SaveProduct(inValue);
            return retVal.Body.SaveProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TekManager.DataService.SaveProductResponse> TekManager.DataService.DataServiceSoap.SaveProductAsync(TekManager.DataService.SaveProductRequest request) {
            return base.Channel.SaveProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<TekManager.DataService.SaveProductResponse> SaveProductAsync(TekManager.DataService.ProductSqlModel product) {
            TekManager.DataService.SaveProductRequest inValue = new TekManager.DataService.SaveProductRequest();
            inValue.Body = new TekManager.DataService.SaveProductRequestBody();
            inValue.Body.product = product;
            return ((TekManager.DataService.DataServiceSoap)(this)).SaveProductAsync(inValue);
        }
        
        public int DeleteProduct(int productId) {
            return base.Channel.DeleteProduct(productId);
        }
        
        public System.Threading.Tasks.Task<int> DeleteProductAsync(int productId) {
            return base.Channel.DeleteProductAsync(productId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TekManager.DataService.GetMembersByEmailOrIdResponse TekManager.DataService.DataServiceSoap.GetMembersByEmailOrId(TekManager.DataService.GetMembersByEmailOrIdRequest request) {
            return base.Channel.GetMembersByEmailOrId(request);
        }
        
        public TekManager.DataService.MemberSqlModel[] GetMembersByEmailOrId(string searchTerm, int count) {
            TekManager.DataService.GetMembersByEmailOrIdRequest inValue = new TekManager.DataService.GetMembersByEmailOrIdRequest();
            inValue.Body = new TekManager.DataService.GetMembersByEmailOrIdRequestBody();
            inValue.Body.searchTerm = searchTerm;
            inValue.Body.count = count;
            TekManager.DataService.GetMembersByEmailOrIdResponse retVal = ((TekManager.DataService.DataServiceSoap)(this)).GetMembersByEmailOrId(inValue);
            return retVal.Body.GetMembersByEmailOrIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TekManager.DataService.GetMembersByEmailOrIdResponse> TekManager.DataService.DataServiceSoap.GetMembersByEmailOrIdAsync(TekManager.DataService.GetMembersByEmailOrIdRequest request) {
            return base.Channel.GetMembersByEmailOrIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TekManager.DataService.GetMembersByEmailOrIdResponse> GetMembersByEmailOrIdAsync(string searchTerm, int count) {
            TekManager.DataService.GetMembersByEmailOrIdRequest inValue = new TekManager.DataService.GetMembersByEmailOrIdRequest();
            inValue.Body = new TekManager.DataService.GetMembersByEmailOrIdRequestBody();
            inValue.Body.searchTerm = searchTerm;
            inValue.Body.count = count;
            return ((TekManager.DataService.DataServiceSoap)(this)).GetMembersByEmailOrIdAsync(inValue);
        }
    }
}
